setupEnv:
  conda_env: envs/3UTRBERT.yaml

downloadSpeciesData:
  output_dir: data/downloaded

isolate3UTRs:
  output_dir: data/3UTRs
  transcriptSection: three_prime_utr,CDS,five_prime_utr

preprocessFlyUTRs:
  output_dir: output/data/flyUTRs
  kmer: 4
  oma_groups: data/oma-groups.txt.gz
  oma_ncbi_map: data/oma-ncbi.txt.gz
  #ncbi_flybase_map: "data/id_validation_table_ncbi_flybase.txt"
  ncbi_geneID_map: data/gene2refseq_Dmel.txt
  geneID_flybase_map: data/GeneID_to_FlybaseID.txt
  #maxSeqLen: null

trainToFlyUTRs:
  test_run: false
  do_train: true
  do_eval: false
  do_predict: false
  do_visualize: false
  output_dir: output/flyTrained
  kmer: 4
  model_type: 3utrfly
  should_continue: false
  model_name_or_path: data/4-new-12w-0
  tokenizer_name: rna4
  evaluate_during_training: true
  do_visualize_during_training: false
  numEpochsBeforeEarlyStopping: 20
  patience: 10
  per_gpu_train_batch_size: 48
  num_train_epochs: 100
  learning_rate: 5e-6
  beta1: 0.9
  beta2: 0.98
  adam_epsilon: 1e-6
  weight_decay: 0.01
  warmup_percent: 0.1
  seed: 6
  eval_all_checkpoints: false
  no_cuda: false
  logging_steps: 100
  save_steps: 1000
  save_total_limit: 2
  overwrite_output_dir: true
  neptune_token:
  neptune_project:
  overwrite_cache: false
  do_lower_case: false
  curriculumLearning: false

RMT:
  memory_size: 10
  block_size: 512
  max_n_segments: 10

mergeUTRsAndDecayRates: #TODO - run with translation efficiency data
  decay_rates: data/translationEfficiency/2h_TE.csv   #"data/results_zygotic_tr_extended_filtered.csv" #"data/maternal-halflifes_modified_filtered.csv"
  transcriptExpression: data/translationEfficiency/transcripts.csv
  output_file: output/data/utrTE.fasta

isolateFullTranscripts:
  output_file: output/data/full_transcripts/Dmela-full_transcripts.fa

getDecayResiduals:
  codon_output: output/data/codons/codon_frequencies.pkl
  residuals: output/data/codons/decayResiduals.fasta
  extraFeatures: output/data/codons/extraFeatures.csv

runViennaRNA:
  output_csv: output/data/codons/vienna_features.csv
  condaPath: /mnt/mr01-home01/m65338lb/.local/bin/micromamba
  maxWorkers: 8
  # RNAfold_path: "/mnt/mr01-home01/m65338lb/.local/share/mamba/envs/inseq/bin/RNAfold"

preprocessData:
  output_dir: output/data/decay
  kmer: 4

fineTuneModel:
  output_dir: output/ftModel
  do_train: true
  do_eval: false
  do_predict: false
  do_visualize: false

predict:
  output_dir: output/predict
  do_train: false
  do_eval: false
  do_predict: true
  do_visualize: false

ablate_features:
  output_dir: output/data/ablations

modelParams:
  model_type: 3utrfly
  task_name: rnadecay
  should_continue: false
  tokenizer_name: rna4
  evaluate_during_training: true
  do_visualize_during_training: false
  projector_dropout: 0.1
  classifier_dropout_prob: 0.1
  learning_rate: 5e-5
  classifier_lr: 1e-4
  #numEpochsBeforeEarlyStopping: 20
  patience: 5
  per_gpu_train_batch_size: 48
  per_gpu_eval_batch_size: 48
  num_train_epochs: 50
  weight_decay: 0.01
  classifier_decay: 0.01
  warmup_percent: 0.1
  #warmup_steps: 7
  seed: 6
  eval_all_checkpoints: false
  no_cuda: false
  logging_steps: 100
  save_steps: 100000
  save_total_limit: 10
  overwrite_output_dir: true
  neptune_token:
  neptune_project:
  overwrite_cache: false
  do_lower_case: false
  curriculumLearning: false

importanceAnalysis:
  output_dir: output/importance
  pickle_file: shap.pkl
  debug: false

visualizeImportance:
  scoresOnly: shapScores.npy
  save_path: visualizeImportance.html
  save_tokenized_path: visualizeImportance_tokenized.html

findMotifs:
  #p_adjust: "fdr_bh"
  output_dir: output/motifs
  control_file: control_seqs.fasta
  motif_file: motif_seqs.fasta
  control_positions: control_positions.txt
  motif_positions: motif_positions.txt
  interest_file: interest_seqs.fasta

runMASTFilter:
  output_dir: output/mastFilter_out

motifsToKeep:
  output_file: motifsToKeep.txt

runAME:
  output_dir: ame_output

correctAME_pvalues:
  output_file: ame_corrected.tsv

microRNABindingEnrichment:
  mirna_file: data/microRNA/Predicted_Targets_Info.default_predictions.txt
  output_dir: output/microRNA
  control_overlap_file: control_overlap.csv
  interest_overlap_file: interest_overlap.csv
  fisher_file: fisher_results.csv

prepRandomizeSeqsAndExtraFeatures:
  sequence_dir: output/data/sanityCheck

randomizeSeqsAndExtraFeatures:
  per_gpu_pred_batch_size: 128

splitHighLowDecay:
  output: output/splitDecay
  high: highDecay.fasta
  low: lowDecay.fasta

runAME_highLowDecay:
  output_dir: ame_output

trainSVM:
  outprefix: output/svm/svm
  mem: 20000 #in MB = 20 GB
  x_foldCV: 5
  threads: 5

SVMpredict:
  output_file: predictions.tsv

runFIMO:
  output_dir: output/fimo_out
  motif_file: data/MEME_suite/Ray2013_rbp_Drosophila_melanogaster_filtered.meme
  fimo_pvalue_threshold: 0.05

prepForMAST:
  output_fasta: output/data/MEME_suite/TEseqs_split_by_utr.fasta

runMAST:
  output_dir: output/mast_out
  output_file: mast_results.txt
  motif_file: data/MEME_suite/Ray2013_rbp_Drosophila_melanogaster.meme
  #sequence_file: output/data/3UTRs/3UTRs.fasta
  mast_pvalue_threshold: 0.05

runTOMTOM:
  output_dir: output/tomtom_out
  motif_file: data/MEME_suite/Ray2013_rbp_Drosophila_melanogaster.meme

codonOnlyClassificationMLP:
  output_dir: output/codonOnlyClassificationMLP
  item: codonOnly
  patience: 7
  per_device_batch_size: 48
  num_train_epochs: 100
  learning_rate: 5e-4
  weight_decay: 0.03
  dropout_percent: 0.75

allExtraFeaturesClassificationMLP:
  output_dir: output/codonOnlyClassificationMLP
  item: allExtraFeatures
  patience: 7
  per_device_batch_size: 48
  num_train_epochs: 100
  learning_rate: 5e-4
  weight_decay: 0.03
  dropout_percent: 0.8
  #seed: 41